name: Test

on:
    push:
    pull_request:


jobs:
    build:
        timeout-minutes: 30
        cancel-timeout-minutes: 30
        name: test
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - uses: Swatinem/rust-cache@v2.7.7

            - name: test
              run: |+
                  cargo test

            # - name: Build
            #   run: |+
            #       export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
            #       export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
            #       export CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++
            #       sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross
            #       rustup target add aarch64-unknown-linux-gnu
            #       cargo build --target aarch64-unknown-linux-gnu --release